### ISSUE TITLE
Negative time

### ISSUE THREAD

**Issue by tissatussa** [sictransit/woodpusher#30]
Today i played a 5m+3s game against Woodpusher v1.2.1 and i won. However, this was due to Woodpusher exceeding the time limit. Playing against other engines (i use CuteChess GUI) the time management seems good, but my game was different : CuteChess allows a human to exceed the time limit, which is a good feature, i think. This simply explains the loss.

I attach the ZIPped CuteChess log : [woodpusher-v1.2.1-loses-on-time-against-human.zip](https://github.com/user-attachments/files/17937403/woodpusher-v1.2.1-loses-on-time-against-human.zip)
It shows the negative times for the Black. I guess you were not aware of this CuteChess functionality and it can easily be solved.

![woodpusher-v1 2 1-loses-on-time-against-human](https://github.com/user-attachments/assets/55539abd-ef6b-48a3-bf02-607ffd07231f)

```
[Event "human vs engine"]
[Site "Holland"]
[Date "2024.11.27"]
[Round "?"]
[White "Woodpusher v1.2.1"]
[Black "Roelof Berkepeis"]
[Result "0-1"]
[ECO "A04"]
[GameDuration "00:13:54"]
[Opening "Reti Opening"]
[PlyCount "60"]
[Termination "time forfeit"]
[TimeControl "300+3"]

1. Nf3 {+0.28/7 5.6s} d6 {21s} 2. e4 {+0.58/7 3.9s} e5 {24s}
3. Bd3 {+0.28/6 3.8s} Be7 {19s} 4. O-O {+0.22/6 3.5s} Bg4 {11s}
5. h3 {+0.34/6 2.9s} Bh5 {5.5s} 6. Nc3 {+0.54/6 2.3s} c6 {3.4s}
7. Be2 {+0.43/6 3.8s} Nf6 {17s} 8. d4 {+0.33/6 5.3s} Nbd7 {4.7s}
9. Be3 {+0.41/4 1.8s} Bxf3 {13s} 10. Bxf3 {+0.67/7 4.9s} exd4 {1.5s}
11. Bxd4 {+0.65/7 4.0s} Qc7 {10s} 12. Qe2 {+0.64/6 3.7s} Ne5 {1.9s}
13. Rad1 {+0.50/7 6.3s} O-O {12s} 14. Rfe1 {+0.39/7 11s} Rad8 {20s}
15. Bg4 {+0.37/7 7.5s} Nfxg4 {12s} 16. hxg4 {+0.31/7 6.4s} b5 {55s}
17. a3 {+0.31/6 3.5s} a5 {13s} 18. f4 {+0.34/6 5.7s} Nc4 {2.7s}
19. b3 {+0.27/7 7.1s} Nxa3 {5.0s} 20. Qf2 {+0.01/7 6.0s} Rb8 {5.9s}
21. e5 {+0.16/7 7.3s} b4 {16s} 22. Na4 {-0.03/7 5.1s} c5 {9.5s}
23. exd6 {+0.51/8 15s} Bxd6 {7.2s} 24. Bxc5 {+0.55/7 4.9s} Bxc5 {26s}
25. Nxc5 {+0.09/8 6.1s} Rbd8 {29s} 26. f5 {+0.20/7 5.6s} Nb5 {5.0s}
27. f6 {+0.41/8 18s} g6 {17s} 28. Rd3 {+0.59/7 5.6s} Rxd3 {8.7s}
29. Nxd3 {+0.39/8 15s} h6 {23s} 30. Re5 {+0.68/9 99s}
Nc3 {38s, White loses on time} 0-1
```

[ i'm on Xubuntu 22.04 ]

**Comment by sictransit** [comment]
No, I didn't have that scenario covered. When it failed to parse a negative time it defaulted to five minutes (and lost). Now it should be OK, as long as it is the opponent that plays on borrowed time. The engine will return `bestmove (none)` if it has no time to think.
